### ISSUE TITLE
Parsing

### ISSUE THREAD

**Issue by shell02** [agatocherry/cub3d#1]
# Parser should :

## Colors
- [x] Get the colors in int format : 0x00000000
- [x] Check that both colors are defined only once

## Textures
- [x] Check that textures end with ".xpm"
- [x] Get the textures and check that they are not defined twice
- [x] Check that we can open and read from the textures files
- [x] Check that all the textures are defined
- [x] (Maybe) Check that the format of the xpm files are 64 x 64

## Map
- [x] Parse the map into a char **map
   - [x] Make a function that count the nomber of line (avec un gnl dediers)
   - [x] Make a function that count the longest len of a line (avec un gnl dediers aussi)
   - [x] Malloc tout ca en double tableau
- [x] Check that the map is the last defined parameter
- [x] BUG -> Avec la taille de la map, ca segfault (mon valgrind ne fonctionne pas sur le pc de Dim a faire a 42 ou autre)
- [x] Norminette
- [x] Static fonctions
- [x] Leaks putain de merde !!!
- [x] Fill map with spaces if a line is smaller than the longest line
- [x] Check that they are no empty lines in the map
- [x] Check that : 
  - [x] if a number is on the first or last row, it is a 1
  - [x] if a number is next to a space, it is a 1
  - [x] if a number is on the first or last column, it is a 1
  `if i = 0 (la première ligne) -> forcément map[i][j] est un 1 ou un espace sinon "Erreur"
else if i = size_map (la dernière ligne) -> forcément map[i][j] est un 1 ou un espace sinon "Erreur"
else if j = 0 (le premier caractère) -> forcément map[i][j] est un 1 ou un espace sinon "Erreur"
else if j = longest_line_size (donc si on est sur le dernier caractère) -> forcément map[i][j] est un 1 ou un espace sinon "Erreur"
else:
if map[i - 1][j] (le caractère juste au dessus) == ' ' -> forcément map[i][j] est un 1 ou un espace sinon "Erreur"
if map[i][j - 1] (le caractère juste a gauche) == ' ' -> forcément map[i][j] est un 1 ou un espace sinon "Erreur"
if map[i][j + 1] (le caractère juste a droite) == ' ' -> forcément map[i][j] est un 1 ou un espace sinon "Erreur"
if map[i + 1][j] (le caractère juste en dessous) == ' ' -> forcément map[i][j] est un 1 ou un espace sinon "Erreur"`
- [x] Check si la map est fermer (1 tout autour) sinon Map invalid
- [x] Check that they are only 0, 1 or "N, S, E, W" on the map
- [x] Replace all spaces with 1
- [x] Get the player init position (int x and int y) and direction (char N or S or E or W)
- [x] Check that the player is positioned only once
- [x] Replace N, S, E or W with 0

This should be a valid map : (S is a space)
S11S
10N1
1001
S11S

This should be an invalid map: (S is a space)
11111111111SSS
1000000N000001
11111111111111

**Comment by agatocherry** [comment]
@shell02 Si jai bien compris, une map n'est pas valide si il y a plusieurs espace consecutif (genre 2)?

**Comment by shell02** [comment]
Non en fait si un chiffre a un espace directement en haut, en bas, à gauche ou a droite, alors ça doit être un 1. Mais si l'espace est en diagonale alors c'est pas oblie d'être un 1

**Comment by agatocherry** [comment]
Donc, dans ces cas la : 
1SSSSS1
1111111
10000E1
1111111
--- 

Non en fait si un chiffre a un espace directement en haut, en bas, à gauche ou a droite, alors ça doit être un 1. Mais si l'espace est en diagonale alors c'est pas oblige d'être un 1
Ca par exemple c'est ok:
1SSSSS1
1111111
10000E1
1111111

Meme ça c'est ok:
1SSSSS1
S11111S
10000E1
S11111S

J'ajoute des 1 mais dans ce cas la :
11111111111SSS
1000000N000001
11111111111111

C'est invalide ?

**Comment by shell02** [comment]
Oui c'est ça. C'est pour ça que je me suis dis c'est mieux de remplacer les espaces par des 1 à la toute fin, et pas avant de verifier si la map est valide ou pas

**Comment by shell02** [comment]
Apres on peut aussi defendre en correction que les espaces pour nous ce sont des murs, mais cet exemple la:
11111111111SSS
1000000N000001
11111111111111
C'est une map non fermée pour moi, qu'en penses-tu ?

**Comment by agatocherry** [comment]
Ahhh ouais dilemme un peu, faut peut etre voir ce que les autres on fais ?

**Comment by agatocherry** [comment]
Apres reflection si je suis daccord avec toi, juste pour etre sure : 
1111S1
1N0001
111111
Cest une map valise ? (juste pour etre sure davoir tout compris

**Comment by shell02** [comment]
Du coup non ce n'est pas valide, le troisième 0 de la deuxième ligne à un espace juste au dessus de lui, donc il devrait etre un 1 pour que ce soit valide

**Comment by agatocherry** [comment]
Ah ok je viens de comprendre !

**Comment by agatocherry** [comment]
Je me suis rajouter les taches, c'est bien ce quil faut faire  ?
Oh et j'ai du mal a comprend ca aussi :/
 Check that :
 if a number is on the first or last row, it is a 1
 if a number is next to a space, it is a 1
 if a number is on the first or last column, it is a 1

**Comment by shell02** [comment]
En gros, d'abord tu parse ta map en ajoutant des espaces a la fin de chaque ligne pour que chaque ligne fasse la meme taille.
Ensuite, il te faut une fonction qui check : 

int i;
int j;
map[i][j];

if i = 0 -> forcément map[i][j] est un 1 ou un espace sinon "Erreur"
else if i = size_map (la dernière ligne) -> forcément map[i][j] est un 1 ou un espace sinon "Erreur"
else if j = 0 -> forcément map[i][j] est un 1 ou un espace sinon "Erreur"
else if j = longest_line_size (donc si on est sur le dernier caractère) -> forcément map[i][j] est un 1 ou un espace sinon "Erreur"
else:
if map[i - 1][j] (le caractère juste au dessus) == ' ' -> forcément map[i][j] est un 1 ou un espace sinon "Erreur"
if map[i][j - 1] (le caractère juste a gauche) == ' ' -> forcément map[i][j] est un 1 ou un espace sinon "Erreur"
if map[i][j + 1] (le caractère juste a droite) == ' ' -> forcément map[i][j] est un 1 ou un espace sinon "Erreur"
if map[i + 1][j] (le caractère juste en dessous) == ' ' -> forcément map[i][j] est un 1 ou un espace sinon "Erreur"

**Comment by shell02** [comment]
Apres c'est ma solution mais si toi tu trouves un truc qui te convient, n'hesites pas a l'implementer comme tu veux !

**Comment by agatocherry** [comment]
Ah d'accord !! Merci beaucoup je me charge de tout ca demain alors ! Merci et desolee je met un peu de temps ahah ^^

**Comment by shell02** [comment]
Super, pas de souci prend le temps qu'il te faut, on est pas presses !

**Comment by shell02** [comment]
J'efface les messages avec des erreurs et je laisse que ceux qui servent à coder la fonction ca te va ?

**Comment by agatocherry** [comment]
Oui vasy !
